---
- name: ensure yum is updated
  yum:
    name: '*'
    state: 'latest'

- name: check if epel repo is already configured.
  stat: "path={{ epel_repofile_path }}"
  register: 'epel_repofile_result'

- name: install epel repo
  yum:
    name: "{{ epel_repo_url }}"
    state: 'present'
  register: 'result'
  until: 'result.rc == 0'
  retries: '5'
  delay: '10'
  when: 'not epel_repofile_result.stat.exists'

- name: import epel gpg key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: 'present'
  when: 'not epel_repofile_result.stat.exists'
  ignore_errors: "{{ ansible_check_mode }}"

- name: ensure epel is installed
  yum:
    name: "{{ packages }}"
    state: 'latest'
  vars:
    packages:
      - 'epel-release'

- name: ensure pip and openssl are installed
  yum:
    name: "{{ packages }}"
    state: 'latest'
  vars:
    packages:
      - 'python-pip'
      - 'openssl'

- name: ensure pexpect is installed
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - 'pexpect'
      - 'pyopenssl'

- name: get selinux status
  command: 'getenforce'
  register: 'selinux_result'
  ignore_errors: 'True'
