---
- name: enable net.ipv4.ip_forward
  sysctl:
    name: 'net.ipv4.ip_forward'
    value: '1'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.icmp_ignore_bogus_error_messages
  sysctl:
    name: 'net.ipv4.icmp_ignore_bogus_error_responses'
    value: '1'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.default.rp_filter
  sysctl:
    name: 'net.ipv4.conf.default.rp_filter'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.default.accept_redirects
  sysctl:
    name: 'net.ipv4.conf.default.accept_redirects'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.default.send_redirects
  sysctl:
    name: 'net.ipv4.conf.default.send_redirects'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.default.log_martians
  sysctl:
    name: 'net.ipv4.conf.default.log_martians'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.all.rp_filter
  sysctl:
    name: 'net.ipv4.conf.all.rp_filter'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.all.accept_redirects
  sysctl:
    name: 'net.ipv4.conf.all.accept_redirects'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.all.send_redirects
  sysctl:
    name: 'net.ipv4.conf.all.send_redirects'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'

- name: enable net.ipv4.conf.all.log_martians
  sysctl:
    name: 'net.ipv4.conf.all.log_martians'
    value: '0'
    sysctl_set: 'yes'
    state: 'present'
    reload: 'yes'
