---

- name: ensure yum packages are up-to-date
  yum:
    name: '*'
    state: 'latest'

- name: ensure git and ansible packages are installed
  yum:
    name: "{{ packages }}"
    state: 'latest'
  vars:
    packages:
      - 'git'
      - 'ansible'
